config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
  get 'baocao/diadiem'
  end

  namespace :admin do
  get 'baocao/kehoach'
  end
    namespace :admin do
  get 'baocao/kehoachmoi'
  end
     namespace :admin do
  get 'baocao/nguoidung'
  end
  namespace :admin do
  get 'homeadmin/index'
  end
  namespace :admin do
  get 'baocao/index'
  end
  namespace :admin do
  get 'places/search'
  end
  namespace :admin do
    resources :comments
  end
 namespace :admin do
 
  end
  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :plans
  end

  namespace :admin do
    resources :dashboards
  end

  namespace :admin do
    resources :users
  end

  namespace :admin do
    resources :posts
  end

  namespace :admin do
    resources :places 
  end

  get 'list/index'

  get 'auth/:provider/callback', to: 'session#create'
  
  get 'users/:id/plans', to: 'users#plans'

  get 'auth/failure', to: redirect('/')
  get 'signout',      to: 'session#destroy', as: 'signout'
  get 'login',        to: 'session#login',   as: 'login'
  get 'signin',       to: 'session#signin',  as: 'signin'

  get 'error',       to: 'api#error',  as: 'error'

  resources :session, only: [:create, :destroy]
  get 'session/create'
  get 'session/destroy'

  get "search/index"
  resources :config_options

  resources :schedule_details

  resources :query_posts

  resources :query_expands

  resources :queries

  resources :crawlers
  resources :api do
    member do
      get 'javo_map_list' 
      get 'index'
      post 'index'

      get 'return_day'
    end
    collection do
      get 'get_plan'
      get 'plans'
      post 'plans'
      get 'getComment'
      post 'comment'
      get 'trip3s_user_by_id'
      get 'showVote'
      post 'vote'
      get 'upload_image'
      post 'upload_image'
      post 'friends'
      get 'response_user'
      post 'response_user'
      post 'detail_by_schedule_id'
      post 'add_friend'
      get 'record'
      get 'trip3sReset'
      post 'trip3sReset'
      get 'trip3sPlan'
      post 'trip3sPlan'
      get 'get_placeIds'
      get 'get_create_plan'
      post 'get_create_plan'
      get 'k_mean'
      get 'add_to_plan'
      get 'load_place_filter'
      get 'load_plan'
      post 'add_day'
      get 'return_day'
      get 'javo_map_list'
      get 'javo_map_all' 
      get 'add_place_to_plan' 
      get 'trip3s_place_by_id'
      get 'index'
      post 'index'
      post 'update_infor'
      get 'item_district'
      post 'item_district'
      get 'item_area'
      post 'item_area'
    end
  end

  resources :post_expands

  resources :schedules

  resources :collection_details

  resources :places do 
    collection do
      get 'search'
      get 'search_all'
      get 'resuft'
    end
  end

  resources :plans do
    collection do
      get 'k_mean'
      get 'search'
      post 'createPlan'
      get 'createPlan'
    end
  end

  resources :post_images

  resources :image_categories

  resources :images do
    collection do 
      get 'upload_image'
      post 'upload_image'
    end
  end

  resources :user_posts

 
  resources :user_expands

  resources :users do
    collection do
      get   'setting'
      post  'setting'
      get   'user-profile',       to: 'users#user_profile' 
      post  'user-profile',       to: 'users#user_profile' 
      get   'user-password',      to: 'users#user_password' 
      post  'user-password',      to: 'users#user_password' 
      get   'user-friends',       to: 'users#user_friend' 
      post  'user-friends',       to: 'users#user_friend' 
      get   'user-confirm',       to: 'users#user_confirm' 
      post  'user-confirm',       to: 'users#user_confirm' 
      get   'user-places',        to: 'users#user_places' 
      post  'user-places',        to: 'users#user_places' 
      get   'user-plans',         to: 'users#user_plans' 
      post  'user-plans',         to: 'users#user_plans' 
      get   'user-collections',   to: 'users#user_collections' 
      post  'user-collections',   to: 'users#user_collections' 
      get   'category-plan',      to: 'users#category_plan' 
      post  'category-plan',      to: 'users#category_plan' 
      get   'category-place',     to: 'users#category_place' 
      post  'category-place',     to: 'users#category_place' 
      get   'category-post',      to: 'users#category_post' 
      post  'category-post',      to: 'users#category_post' 
      get   'city',               to: 'users#category_city' 
      post  'city',               to: 'users#category_city' 
    end
  end
  resources :post_categories

 
  resources :posts do
    resources :comments
  end
  resources :types

  resources :categories
  root 'places#index' 
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :post

  
  def thumbnail
     _thumbnail = PostExpand.where("post_id = ? and expand_name = 'post_thumbnail2'", post_id).last
     if _thumbnail.present?
       return _thumbnail.expand_value
     end
     return 'default.png'
  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /admin/places
  # GET /admin/places.json
  def index
    @places = Place.all
    @places_all=Place.all.paginate(page: params[:page])
  end
   def resuft
     @places = Place.all
    @posts  = Post.select("*").joins(:place).order('post_view desc').limit(4)
    @places_category = Category.select("*").joins(:type).where(:types => {:type_name => 'type_category_place'})
    @places_cate_all=Category.select("*").joins(:type).where(:types => {:type_name => 'type_category_place',:type_name => 'type_city',:type_name => 'type_district',:type_name => 'type_area',:type_name => 'type_diding_place',:type_name => 'type_property_place',:type_name => 'type_cuisine_place',:type_name => 'type_purpose_place'}).limit(10)
  end
  # GET /admin/places/1
  # GET /admin/places/1.json
  def show
  end

  # GET /admin/places/new
  def new
    @place = Place.new
      @places_cate_all=Post.select("*").where(:post_title => {:type_name => 'type_category_place'})
  #  @places_three_limit=Post.select("*").order('post_review desc').limit(3,100)
    @places_category  = Category.select("*").joins(:type).where(:types => {:type_name => 'type_category_place'}) 

  end

  # GET /admin/places/1/edit
  def edit
     @places_category  = Category.select("*").joins(:type).where(:types => {:type_name => 'type_category_place'}) 
  end

  # POST /admin/places
  # POST /admin/places.json
def create
     status = true
    post_id = ''
      _post = {
        :post_title     => params[:post][:plan_title],
        :post_content   => params[:post][:plan_content], 
        :post_type =>  'type_place'
      }
      post_id = savePost(_post)
      _place={
          :post_id    => post_id,
          :place_lat   => params[:place]["place_lat"],
          :place_lng => params[:place]["place_lng"],
          :place_ticket   => 0,
          :place_open => params[:place]["place_open"],
          :place_close => params[:place]["place_close"],
          :place_late=> params[:place]["place_late"],
          :place_address=> params[:place]["place_address"]
      }
    @place = Place.new(_place)
    #session[:user_id]
    _userpost={
        :user_id => 1,
        :post_id => post_id
    }
    saveUserPost(_userpost);
    _postcate={
      :post_id => post_id,
      :type_id => params[:post]["category_id"]
    }
    savePostCategories(_postcate);
     if @place.save
       redirect_to @place
      else
        render action: 'new'
      end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end
# DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
   def search
      sql5 = " select B.post_title,A.place_address,A.post_id,B.id from places A, posts B where B.id=A.post_id and B.post_title like '%#{params[:search]}%' "
      @places_search=Place.paginate_by_sql(sql5, :page => params[:page], :per_page => 10)
      @places=Post.all.paginate(page: params[:page])
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.joins(:post).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:post_id, :place_lat, :place_lng, :place_ticket, :place_open, :place_close, :place_late, :place_choice)
    end
    #action load places filter by city, district,area, cate,cuisine, property,dide, purpose
 
 
  def load_place_filter
    #All place none filter
    places    = Post.select("posts.id,
                  posts.post_title,
                  posts.post_content,
                  posts.post_thumbnail,
                  posts.post_url,
                  posts.post_point,
                  posts.post_review,
                  posts.post_view")
            .distinct
            .joins(:place,:post_category =>{:type=>:category})
            .order('post_view desc')
    #Check condition filter
    check_filter  = false
    location_arr  = Array.new
    #Check city in filter
    if params[:allIds].present? && params[:allIds] !=''
      #places = places.where(:types => {:category_id=> params[:cityIds]})
      location_arr = {
        :ids  => params[:allIds],
        :name   => 'type_city'}
      check_filter =true
    end
    #Get all place of location
    if location_arr.present?
      check_filter =true
      places = places.where("posts.id in (?)",places.select("posts.id").where(:types => {:category_id=> location_arr[:ids],:type_name=> location_arr[:name]}) )
    end
    if check_filter ==false
      places = places.where(:types => {:type_name=> 'type_category_place'})
    end

    _count = places.count('posts.id')

    offset = 0;
    limit = 12;
    if params[:offset].present?
      offset = params[:offset]
    end
    if params[:limit].present?
      limit = params[:limit]
    end

    render json: {
        :count  => _count,
        :places => return_place_ids(places,offset,limit)
        }
  end

  def return_place_ids(places, offset=0,limit=12)
    places_temp   =   places.offset(offset).limit(limit)

    arr     = Array.new 
    
    places_temp.each do |place|
      #filter category of place
      categories   =  filter_category place.id, 'type_category_place'
      arrCate    =  Array.new
      categories.each do |cate|
        arrCate << cate.type.category.cate_name
      end

      temp_place   =  {
        'post_id'     =>  place.id  ,
        'post_title'  =>  place.post_title  ,
        'post_content'  =>  place.post_content  ,
        'post_thumbnail'=>  place.post_thumbnail  ,
        'permalink'   =>  place.post_url,
        'avatar'    =>  place.post_thumbnail  ,
        'rating'    =>  place.post_view ,
        'post_view'   =>  place.post_view ,
        'post_review'   =>  place.post_review ,
        'post_point'  =>  place.post_point  ,
        'favorite'    =>  ''  ,
        'category'    =>  arrCate.to_sentence   ,
        'place_lat'   =>  place.place[0].place_lat,
        'place_lng'   =>  place.place[0].place_lng,
        'place_id'    =>  place.place[0].id,
        'location'    =>  place.place[0].place_address  ,
        'place_time'  =>  place.place[0].place_time,
        'place_open'  =>  place.place[0].place_open,
        'place_close' =>  place.place[0].place_close,
        'place_late'  =>  place.place[0].place_late,
        'place_choise'  =>  place.place[0].place_choice,
        'place_ticket'  =>  place.place[0].place_ticket,
        'place_min'   =>  place.place[0].place_min,
        'place_max'   =>  place.place[0].place_max
      }
      arr << temp_place
    end
    
    return arr
  end
  def filter_category (post_id ,type_name)
    postCategories  = PostCategory.select("*")
                     .joins(:type=>:category)
                     .where(:types => {:type_name => "#{type_name}"}, 'post_id' => "#{post_id}")
    return postCategories
  end
end
def savePost post
    if post.nil?
      return false
    end

    tmpPost = Post.new
     tmpPost.post_title    =   post[:post_title]
     tmpPost.post_content  =   post[:post_content]
     tmpPost.post_type     =   'type_place'
     tmpPost.post_view     =   0
     tmpPost.post_review   =   0
     tmpPost.post_point    =   0
    if tmpPost.save
      return tmpPost.id
    end
      puts "error save post"
    return false
  end
def saveUserPost usepost
    if usepost.nil?
      return false
    end

    tmpUserPost = UserPost.new
     tmpUserPost.post_id    =   usepost[:post_id]
     tmpUserPost.user_id    =   usepost[:user_id]
    if tmpUserPost.save
      return tmpUserPost.id
    end
      puts "error save UserPost"
    return false
  end
  def savePostCategories postcate
    if postcate.nil?
      return false
    end

    tmpPostCategory = PostCategory.new
     tmpPostCategory.post_id    =   postcate[:post_id]
     tmpPostCategory.type_id    =   postcate[:type_id]
    if tmpPostCategory.save
      return tmpPostCategory.id
    end
      puts "error save PostCategory"
    return false
  end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/places/_form.html.erb
<section id="main-content">

<div class="container">
<div class="new_places">
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-6">
    <label>Tên địa điểm</label><br>
    <input type="text" name="post[post_title]" class="form-control left" id="post-post_title"  required="required" style ="width:100%"><br>
    <label>Địa chỉ</label><br>
    <input type="text" name="place[place_address]" class="form-control left" id="post-post_content"  required="required" style ="width:100%"><br>
    <label>Mô tả địa điểm</label>
    <textarea name="post[post_content]" class="form-control left" id="post-post_content"  required="required" style ="width:100%;height:170px;"></textarea><br>
  </div>
  <div class="col-md-6">
    <label>Loai dia diem</label><br>
    <select name="post[category_id]">
    <%@places_category.each do |cate|%>
    <option value="  <%=cate.id%>   ">  <%=cate.cate_name%>   </option>
    <%end%>
    </select><br>
     <label>Lat</label><br>
    <!-- <input type="text" name="post[post_title]" class="form-control left" id="post-post_title"  required="required" style ="width:100%"> -->
    <%= f.text_field :place_lat %>
    <br>
    <label>Long</label><br>
    <!-- <input type="text" name="post[post_content]" class="form-control left" id="post-post_content"  required="required" style ="width:100%"> -->

    <%= f.text_field :place_lng %>
    <br>
     <div class="field">
      <div class="field">
    <label>Điểm ưu tiên</label><br>
    <%= f.text_field :place_choice %>
  </div>
   <label>Thời gian mở cửa</label><br>
    <%= f.text_field :place_open %>
  </div>
  <div class="field">
   <label>Thời gian đóng cửa</label><br>
    <%= f.text_field :place_close %>
  </div>
  <div class="field">
    <label>Thời gian nhận khách cuối cùng</label><br>
    <%= f.text_field :place_late %>
  </div>
  <div class="field">
    <label>Giá thấp nhất</label><br>
    <%= f.text_field :place_min %>
  </div>
  <div class="field">
    <label>Giá cao nhất</label><br>
    <%= f.text_field :place_max %>
  </div>
   <div class="field">
    <label>Thời gian lưu lại</label><br>
    <%= f.text_field :place_max %>
  </div>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>
</section>

app/views/admin/places/_formedit.html.erb
<style type="text/css">
input{width: 100% !important;}
</style>
<section id="main-content">
<div class="container">
<div class="new_places">
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
    <label>Địa chỉ</label><br>
    <%= f.text_field :place_address %>
    <label>Loai dia diem</label><br>
    <select name="post[category_id]">
    <%@places_category.each do |cate|%>
    <option value="  <%=cate.id%>   ">  <%=cate.cate_name%>   </option>
    <%end%>
    </select><br>
     <label>Lat</label><br>
    <!-- <input type="text" name="post[post_title]" class="form-control left" id="post-post_title"  required="required" style ="width:100%"> -->
    <%= f.text_field :place_lat %>
    <br>
    <label>Long</label><br>
    <!-- <input type="text" name="post[post_content]" class="form-control left" id="post-post_content"  required="required" style ="width:100%"> -->

    <%= f.text_field :place_lng %>
    <br>
    
      <div class="field">
    <label>Điểm ưu tiên</label><br>
    <%= f.text_field :place_choice %>
  </div>
   <label>Thời gian mở cửa</label><br>
    <%= f.text_field :place_open %>
  </div>
  <div class="field">
   <label>Thời gian đóng cửa</label><br>
    <%= f.text_field :place_close %>
  </div>
  <div class="field">
    <label>Thời gian nhận khách cuối cùng</label><br>
    <%= f.text_field :place_late %>
  </div>
  <div class="field">
    <label>Giá thấp nhất</label><br>
    <%= f.text_field :place_min %>
  </div>
  <div class="field">
    <label>Giá cao nhất</label><br>
    <%= f.text_field :place_max %>
  </div>
   <div class="field">
    <label>Thời gian lưu lại</label><br>
    <%= f.text_field :place_time %>
  </div>
  </div>
</div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</section>

app/views/admin/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'formedit' %>

<%= link_to 'Show', [:admin, @place] %> |
<%= link_to 'Back', admin_places_path %>

app/views/admin/places/index.html.erb
<section id="main-content">
<div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              <h2>Danh Sách Địa Điểm</h2>
                               <button type="button" class="btn btn-success pull-right"><%= link_to '+ Thêm mới địa điểm', new_admin_place_path %></button>
                          </header>
                          <h1>Tìm kiếm</h1>
                            <%= form_tag admin_places_search_path,:action=>'admin/places/search', :method => 'get', :id => 'search_form' do %>
                            <%= text_field_tag :search, params[:search] %>
                      <%= submit_tag "Search", :name => nil,:id=>"btn-search",:class=>"btn btn-success",:placeholder =>"Enter places" %></br>
                      
<% end %>
                          <table class="table table-striped table-advance table-hover">
                           <tbody>
                              <tr>
                                 <th><i class="icon_profile"></i> Tên Địa Điểm</th>
                                 <th><i class="icon_calendar"></i> Địa Chỉ</th>
                                 <th><i class="icon_cogs"></i> Hành Động</th>
                              </tr>
                              <% @places_all.each do |place| %>
                              <tr>
                                  <td><%= place.post.post_title %></td>
                                  <td><%= place.place_address %></td>
                                   <td>
                                  <div class="btn-group">
                                      <%= link_to 'Xem', [:admin, place] %>
                                      ||<%= link_to 'Sửa', edit_admin_place_path(place) %>
                                      ||<%= link_to 'Xóa', [:admin, place], method: :delete, data: { confirm: 'Are you sure?' } %>
                                  </div>
                                  </td>
                                </tr>
                              <% end %>
                           </tbody>
                        </table>
                        <%= will_paginate @places_all %>
                      </section>
 
<br>
</section>

app/views/admin/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_places_path %>

app/views/admin/places/search.html.erb
<section id="main-content">
<div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              <h2>Danh Sách Người Dùng Mới</h2>
                            
                          </header>
                        
                          <table class="table table-striped table-advance table-hover">
                           <tbody>
                              <tr>
                                 <th><i class="icon_profile"></i> Tên Địa Điểm</th>
                                 <th><i class="icon_calendar"></i> Địa Chỉ</th>
                                 <th><i class="icon_cogs"></i> Hành Động</th>
                              </tr>
                            <% for place in @places_search %>
                              <tr>
                                  <td><%= place.post.post_title %></td>
                                  <td><%= place.place_address %></td>
                                   <td>
                                  <div class="btn-group">
                                      <%= link_to 'Xem', [:admin, place] %>
                                      ||<%= link_to 'Sửa', edit_admin_place_path(place) %>
                                      ||<%= link_to 'Xóa', [:admin, place], method: :delete, data: { confirm: 'Are you sure?' } %>
                                  </div>
                                  </td>
                                </tr>
                              <% end %>
                           </tbody>
                        </table>
                        <%= will_paginate @places_search %>
                      </section>
 
<br>
</section>

app/views/admin/places/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_place_path(@place) %> |
<%= link_to 'Back', admin_places_path %>