config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
  get 'baocao/diadiem'
  end

  namespace :admin do
  get 'baocao/kehoach'
  end
    namespace :admin do
  get 'baocao/kehoachmoi'
  end
     namespace :admin do
  get 'baocao/nguoidung'
  end
  namespace :admin do
  get 'homeadmin/index'
  end
  namespace :admin do
  get 'baocao/index'
  end
  namespace :admin do
  get 'places/search'
  end
  namespace :admin do
    resources :comments
  end
 namespace :admin do
 
  end
  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :plans
  end

  namespace :admin do
    resources :dashboards
  end

  namespace :admin do
    resources :users
  end

  namespace :admin do
    resources :posts
  end

  namespace :admin do
    resources :places 
  end

  get 'list/index'

  get 'auth/:provider/callback', to: 'session#create'
  
  get 'users/:id/plans', to: 'users#plans'

  get 'auth/failure', to: redirect('/')
  get 'signout',      to: 'session#destroy', as: 'signout'
  get 'login',        to: 'session#login',   as: 'login'
  get 'signin',       to: 'session#signin',  as: 'signin'

  get 'error',       to: 'api#error',  as: 'error'

  resources :session, only: [:create, :destroy]
  get 'session/create'
  get 'session/destroy'

  get "search/index"
  resources :config_options

  resources :schedule_details

  resources :query_posts

  resources :query_expands

  resources :queries

  resources :crawlers
  resources :api do
    member do
      get 'javo_map_list' 
      get 'index'
      post 'index'

      get 'return_day'
    end
    collection do
      get 'get_plan'
      get 'plans'
      post 'plans'
      get 'getComment'
      post 'comment'
      get 'trip3s_user_by_id'
      get 'showVote'
      post 'vote'
      get 'upload_image'
      post 'upload_image'
      post 'friends'
      get 'response_user'
      post 'response_user'
      post 'detail_by_schedule_id'
      post 'add_friend'
      get 'record'
      get 'trip3sReset'
      post 'trip3sReset'
      get 'trip3sPlan'
      post 'trip3sPlan'
      get 'get_placeIds'
      get 'get_create_plan'
      post 'get_create_plan'
      get 'k_mean'
      get 'add_to_plan'
      get 'load_place_filter'
      get 'load_plan'
      post 'add_day'
      get 'return_day'
      get 'javo_map_list'
      get 'javo_map_all' 
      get 'add_place_to_plan' 
      get 'trip3s_place_by_id'
      get 'index'
      post 'index'
      post 'update_infor'
      get 'item_district'
      post 'item_district'
      get 'item_area'
      post 'item_area'
    end
  end

  resources :post_expands

  resources :schedules

  resources :collection_details

  resources :places do 
    collection do
      get 'search'
      get 'search_all'
      get 'resuft'
    end
  end

  resources :plans do
    collection do
      get 'k_mean'
      get 'search'
      post 'createPlan'
      get 'createPlan'
    end
  end

  resources :post_images

  resources :image_categories

  resources :images do
    collection do 
      get 'upload_image'
      post 'upload_image'
    end
  end

  resources :user_posts

 
  resources :user_expands

  resources :users do
    collection do
      get   'setting'
      post  'setting'
      get   'user-profile',       to: 'users#user_profile' 
      post  'user-profile',       to: 'users#user_profile' 
      get   'user-password',      to: 'users#user_password' 
      post  'user-password',      to: 'users#user_password' 
      get   'user-friends',       to: 'users#user_friend' 
      post  'user-friends',       to: 'users#user_friend' 
      get   'user-confirm',       to: 'users#user_confirm' 
      post  'user-confirm',       to: 'users#user_confirm' 
      get   'user-places',        to: 'users#user_places' 
      post  'user-places',        to: 'users#user_places' 
      get   'user-plans',         to: 'users#user_plans' 
      post  'user-plans',         to: 'users#user_plans' 
      get   'user-collections',   to: 'users#user_collections' 
      post  'user-collections',   to: 'users#user_collections' 
      get   'category-plan',      to: 'users#category_plan' 
      post  'category-plan',      to: 'users#category_plan' 
      get   'category-place',     to: 'users#category_place' 
      post  'category-place',     to: 'users#category_place' 
      get   'category-post',      to: 'users#category_post' 
      post  'category-post',      to: 'users#category_post' 
      get   'city',               to: 'users#category_city' 
      post  'city',               to: 'users#category_city' 
    end
  end
  resources :post_categories

 
  resources :posts do
    resources :comments
  end
  resources :types

  resources :categories
  root 'places#index' 
end

app/models/query_expand.rb
class QueryExpand < ActiveRecord::Base
  belongs_to :query
end

app/controllers/query_expands_controller.rb
class QueryExpandsController < ApplicationController
  before_action :set_query_expand, only: [:show, :edit, :update, :destroy]

  # GET /query_expands
  # GET /query_expands.json
  def index
    @query_expands = QueryExpand.all
  end

  # GET /query_expands/1
  # GET /query_expands/1.json
  def show
  end

  # GET /query_expands/new
  def new
    @query_expand = QueryExpand.new
  end

  # GET /query_expands/1/edit
  def edit
  end

  # POST /query_expands
  # POST /query_expands.json
  def create
    @query_expand = QueryExpand.new(query_expand_params)

    respond_to do |format|
      if @query_expand.save
        format.html { redirect_to @query_expand, notice: 'Query expand was successfully created.' }
        format.json { render action: 'show', status: :created, location: @query_expand }
      else
        format.html { render action: 'new' }
        format.json { render json: @query_expand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /query_expands/1
  # PATCH/PUT /query_expands/1.json
  def update
    respond_to do |format|
      if @query_expand.update(query_expand_params)
        format.html { redirect_to @query_expand, notice: 'Query expand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @query_expand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /query_expands/1
  # DELETE /query_expands/1.json
  def destroy
    @query_expand.destroy
    respond_to do |format|
      format.html { redirect_to query_expands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query_expand
      @query_expand = QueryExpand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_expand_params
      params.require(:query_expand).permit(:query_id, :expand_name, :expand_value)
    end
end

app/helpers/query_expands_helper.rb
module QueryExpandsHelper
end

app/views/query_expands/_form.html.erb
<%= form_for(@query_expand) do |f| %>
  <% if @query_expand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query_expand.errors.count, "error") %> prohibited this query_expand from being saved:</h2>

      <ul>
      <% @query_expand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br>
    <%= f.text_field :query %>
  </div>
  <div class="field">
    <%= f.label :expand_name %><br>
    <%= f.text_field :expand_name %>
  </div>
  <div class="field">
    <%= f.label :expand_value %><br>
    <%= f.text_field :expand_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/query_expands/edit.html.erb
<h1>Editing query_expand</h1>

<%= render 'form' %>

<%= link_to 'Show', @query_expand %> |
<%= link_to 'Back', query_expands_path %>

app/views/query_expands/index.html.erb
<h1>Listing query_expands</h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th>Expand name</th>
      <th>Expand value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @query_expands.each do |query_expand| %>
      <tr>
        <td><%= query_expand.query %></td>
        <td><%= query_expand.expand_name %></td>
        <td><%= query_expand.expand_value %></td>
        <td><%= link_to 'Show', query_expand %></td>
        <td><%= link_to 'Edit', edit_query_expand_path(query_expand) %></td>
        <td><%= link_to 'Destroy', query_expand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query expand', new_query_expand_path %>

app/views/query_expands/new.html.erb
<h1>New query_expand</h1>

<%= render 'form' %>

<%= link_to 'Back', query_expands_path %>

app/views/query_expands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= @query_expand.query %>
</p>

<p>
  <strong>Expand name:</strong>
  <%= @query_expand.expand_name %>
</p>

<p>
  <strong>Expand value:</strong>
  <%= @query_expand.expand_value %>
</p>

<%= link_to 'Edit', edit_query_expand_path(@query_expand) %> |
<%= link_to 'Back', query_expands_path %>