config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
  get 'baocao/diadiem'
  end

  namespace :admin do
  get 'baocao/kehoach'
  end
    namespace :admin do
  get 'baocao/kehoachmoi'
  end
     namespace :admin do
  get 'baocao/nguoidung'
  end
  namespace :admin do
  get 'homeadmin/index'
  end
  namespace :admin do
  get 'baocao/index'
  end
  namespace :admin do
  get 'places/search'
  end
  namespace :admin do
    resources :comments
  end
 namespace :admin do
 
  end
  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :plans
  end

  namespace :admin do
    resources :dashboards
  end

  namespace :admin do
    resources :users
  end

  namespace :admin do
    resources :posts
  end

  namespace :admin do
    resources :places 
  end

  get 'list/index'

  get 'auth/:provider/callback', to: 'session#create'
  
  get 'users/:id/plans', to: 'users#plans'

  get 'auth/failure', to: redirect('/')
  get 'signout',      to: 'session#destroy', as: 'signout'
  get 'login',        to: 'session#login',   as: 'login'
  get 'signin',       to: 'session#signin',  as: 'signin'

  get 'error',       to: 'api#error',  as: 'error'

  resources :session, only: [:create, :destroy]
  get 'session/create'
  get 'session/destroy'

  get "search/index"
  resources :config_options

  resources :schedule_details

  resources :query_posts

  resources :query_expands

  resources :queries

  resources :crawlers
  resources :api do
    member do
      get 'javo_map_list' 
      get 'index'
      post 'index'

      get 'return_day'
    end
    collection do
      get 'get_plan'
      get 'plans'
      post 'plans'
      get 'getComment'
      post 'comment'
      get 'trip3s_user_by_id'
      get 'showVote'
      post 'vote'
      get 'upload_image'
      post 'upload_image'
      post 'friends'
      get 'response_user'
      post 'response_user'
      post 'detail_by_schedule_id'
      post 'add_friend'
      get 'record'
      get 'trip3sReset'
      post 'trip3sReset'
      get 'trip3sPlan'
      post 'trip3sPlan'
      get 'get_placeIds'
      get 'get_create_plan'
      post 'get_create_plan'
      get 'k_mean'
      get 'add_to_plan'
      get 'load_place_filter'
      get 'load_plan'
      post 'add_day'
      get 'return_day'
      get 'javo_map_list'
      get 'javo_map_all' 
      get 'add_place_to_plan' 
      get 'trip3s_place_by_id'
      get 'index'
      post 'index'
      post 'update_infor'
      get 'item_district'
      post 'item_district'
      get 'item_area'
      post 'item_area'
    end
  end

  resources :post_expands

  resources :schedules

  resources :collection_details

  resources :places do 
    collection do
      get 'search'
      get 'search_all'
      get 'resuft'
    end
  end

  resources :plans do
    collection do
      get 'k_mean'
      get 'search'
      post 'createPlan'
      get 'createPlan'
    end
  end

  resources :post_images

  resources :image_categories

  resources :images do
    collection do 
      get 'upload_image'
      post 'upload_image'
    end
  end

  resources :user_posts

 
  resources :user_expands

  resources :users do
    collection do
      get   'setting'
      post  'setting'
      get   'user-profile',       to: 'users#user_profile' 
      post  'user-profile',       to: 'users#user_profile' 
      get   'user-password',      to: 'users#user_password' 
      post  'user-password',      to: 'users#user_password' 
      get   'user-friends',       to: 'users#user_friend' 
      post  'user-friends',       to: 'users#user_friend' 
      get   'user-confirm',       to: 'users#user_confirm' 
      post  'user-confirm',       to: 'users#user_confirm' 
      get   'user-places',        to: 'users#user_places' 
      post  'user-places',        to: 'users#user_places' 
      get   'user-plans',         to: 'users#user_plans' 
      post  'user-plans',         to: 'users#user_plans' 
      get   'user-collections',   to: 'users#user_collections' 
      post  'user-collections',   to: 'users#user_collections' 
      get   'category-plan',      to: 'users#category_plan' 
      post  'category-plan',      to: 'users#category_plan' 
      get   'category-place',     to: 'users#category_place' 
      post  'category-place',     to: 'users#category_place' 
      get   'category-post',      to: 'users#category_post' 
      post  'category-post',      to: 'users#category_post' 
      get   'city',               to: 'users#category_city' 
      post  'city',               to: 'users#category_city' 
    end
  end
  resources :post_categories

 
  resources :posts do
    resources :comments
  end
  resources :types

  resources :categories
  root 'places#index' 
end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  belongs_to :image
  belongs_to :post
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]

  # GET /post_images
  # GET /post_images.json
  def index
    @post_images = PostImage.all
  end

  # GET /post_images/1
  # GET /post_images/1.json
  def show
  end

  # GET /post_images/new
  def new
    @post_image = PostImage.new
  end

  # GET /post_images/1/edit
  def edit
  end

  # POST /post_images
  # POST /post_images.json
  def create
    @post_image = PostImage.new(post_image_params)

    respond_to do |format|
      if @post_image.save
        format.html { redirect_to @post_image, notice: 'Post image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post_image }
      else
        format.html { render action: 'new' }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_images/1
  # PATCH/PUT /post_images/1.json
  def update
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to @post_image, notice: 'Post image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_images/1
  # DELETE /post_images/1.json
  def destroy
    @post_image.destroy
    respond_to do |format|
      format.html { redirect_to post_images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_image_params
      params.require(:post_image).permit(:image_id, :post_id)
    end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_form.html.erb
<%= form_for(@post_image) do |f| %>
  <% if @post_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_image.errors.count, "error") %> prohibited this post_image from being saved:</h2>

      <ul>
      <% @post_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_images/edit.html.erb
<h1>Editing post_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_image %> |
<%= link_to 'Back', post_images_path %>

app/views/post_images/index.html.erb
<h1>Listing post_images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @post_images.each do |post_image| %>
      <tr>
        <td><%= post_image.image %></td>
        <td><%= post_image.post %></td>
        <td><%= link_to 'Show', post_image %></td>
        <td><%= link_to 'Edit', edit_post_image_path(post_image) %></td>
        <td><%= link_to 'Destroy', post_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post image', new_post_image_path %>

app/views/post_images/new.html.erb
<h1>New post_image</h1>

<%= render 'form' %>

<%= link_to 'Back', post_images_path %>

app/views/post_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @post_image.image %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_image.post %>
</p>

<%= link_to 'Edit', edit_post_image_path(@post_image) %> |
<%= link_to 'Back', post_images_path %>